Models/DeptModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace CRUDMVC.Models
{
    public class DeptModel
    {
        [Display(Name = "Department ID")]
        public int DeptID { get; set; }

        [Display(Name = "Department Name")]
   //   [Required(ErrorMessage = "Department Name is required")]
       // [Remote("DeptNameExists", "Department", HttpMethod = "POST", ErrorMessage = "Department name is already exist.")]
        public string DeptName { get; set; }

        [Display(Name = "Manager Name")]
        [Required(ErrorMessage = " Manager Name is required")]
        public string MGRName { get; set; }

        [Display(Name = "Manager Employee ID")]
  //    [Required(ErrorMessage ="Manager Employee ID is required")]
        public int MGREMPNO { get; set; }
    }
}

Models/EmpModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CRUDMVC.Models
{
    public class EmpModel
    {
        [Display(Name = "Id")]
        public int Empid { get; set; }

      //[Required(ErrorMessage = "First name is required.")]
        public string Name { get; set; }

      //[Required(ErrorMessage = "City is required.")]
        public string City { get; set; }

      //[Required(ErrorMessage = "Address is required.")]
        public string Address { get; set; }
    }
}

Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRUDMVC.Repository;
using CRUDMVC.Models;



namespace CRUDMVC.Controllers
{
    public class DepartmentController : Controller
    {
        DeptRepository DeptRepo = new DeptRepository();
       // private TestEntities db = new TestEntities();
        public ActionResult ListDepartment()
        {
            ModelState.Clear();
            return View(DeptRepo.ListDepartment());
        }
        //public JsonResult DeptNameExists(string username)
        //{
            
        //   // return Json(!Any(u => u.DeptName == DeptName), JsonRequestBehavior.AllowGet);
        //    //return Json(!String.Equals(username,  StringComparison.OrdinalIgnoreCase));
        //}
        //GET
        public ActionResult AddDepartment()
        {
            try
            {
                return View();
            }
            catch(Exception ex)
            {

                return View();
            }
            
        }
        [HttpPost]
        public ActionResult CheckDeptAvailability(DeptModel dmp)
        {
            DeptRepo.CheckDeptAvailability(dmp);
            return View();
        }
        [HttpPost]
        public ActionResult AddDepartment(DeptModel dmp)
        {
            try
            {
                DeptRepo.AddDepartment(dmp);
                ViewBag.SucessMessage = "Department is added successfully.";
                return View();
                //return RedirectToAction("ListDepartment");
            }
            catch (Exception ex) { return View(); }
        }
        public ActionResult EditDeptDetails(int id)
        {
            return View(DeptRepo.ListDepartment().Find(Dep => Dep.DeptID == id));
        }
        [HttpPost]
    public ActionResult EditDeptDetails(int id, DeptModel dept)
        {
            try
            {
                DeptRepo.UpdateDepartment(dept);
                return RedirectToAction("ListDepartment");
            }
            catch { return View(); }
        }
        public ActionResult DeleteDept(int id)
        {
            try
            {
                DeptRepo.DeleteDepartment(id);
                return RedirectToAction("ListDepartment");
            }
            catch { return View(); }
        }

    }
}

Controllers/EmployeeController.cs
using CRUDMVC.Models;
using CRUDMVC.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRUDMVC.Controllers
{
    public class EmployeeController : Controller
    {
        EmpRepository EmpRepo = new EmpRepository();
        // GET: Employee/GetAllEmpDetails    
        public ActionResult GetAllEmpDetails()
        {
            //EmpRepository EmpRepo = new EmpRepository();
            ModelState.Clear();
            return View(EmpRepo.GetAllEmployees());
        }
        // get: employee/addemployee    
        public ActionResult AddEmployee()
        {
            return View();
        }

        // POST: Employee/AddEmployee    
        [HttpPost]
        public ActionResult AddEmployee(EmpModel emp)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //      emprepository emprepo = new emprepository();

                    if (EmpRepo.AddEmployee(emp))
                    {
                        ViewBag.message = "employee details added successfully";
                    }
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Employee/EditEmpDetails/5    
        public ActionResult EditEmpDetails(int id)
        {
           //EmpRepository EmpRepo = new EmpRepository();



            return View(EmpRepo.GetAllEmployees().Find(Emp => Emp.Empid == id));

        }

        // POST: Employee/EditEmpDetails/5    
        [HttpPost]

        public ActionResult EditEmpDetails(int id, EmpModel obj)
        {
            try
            {
                //       emprepository emprepo = new emprepository();

                EmpRepo.UpdateEmployee(obj);


                return RedirectToAction("GetAllEmpDetails");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        //GET: Employee/DeleteEmp/5    
        public ActionResult DeleteEmp(int id)
        {
            try
            {
                //EmpRepository EmpRepo = new EmpRepository();
                if (EmpRepo.DeleteEmployee(id))
                {
                    ViewBag.Message = "Employee details deleted successfully";

                }
                return RedirectToAction("GetAllEmpDetails");

            }
            catch (Exception)
            {
                return View();
            }
        }
    }
}

Views/Department/AddDepartment.cshtml
@model CRUDMVC.Models.DeptModel


@using (Html.BeginForm("AddDepartment", "Department",FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>DeptModel</h4>
    <hr />
    <div class="form-group">
        @if (@ViewBag.SucessMessage != null)
        {
            <label style="color: green; margin-left: 13%;">@ViewBag.SucessMessage</label>
        }
    </div>




    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @*<div class="form-group">
            @Html.LabelFor(model => model.DeptID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeptID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeptID, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.DeptName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DeptName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DeptName, "", new { @class = "text-danger" })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MGRName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MGRName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MGRName, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.MGREMPNO, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MGREMPNO, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MGREMPNO, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="search" value="Name Availabilty" class="btn btn-default" />
        </div>
        <div class="col-md-offset-3">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
    
    <div>
        @Html.ActionLink("Back to List", "ListDepartment")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>
}

Views/Department/EditDeptDetails.cshtml
@model CRUDMVC.Models.DeptModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>DeptModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.DeptID)
    @*<div class="form-group">
            @Html.LabelFor(model => model.DeptID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeptID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeptID, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.DeptName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DeptName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DeptName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MGRName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MGRName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MGRName, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.DeptID)

    <div class="form-group">
            @Html.LabelFor(model => model.MGREMPNO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MGREMPNO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MGREMPNO, "", new { @class = "text-danger" })
            </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "ListDepartment")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Department/ListDepartment.cshtml
@model IEnumerable<CRUDMVC.Models.DeptModel>

<p>
    @Html.ActionLink("Create New", "AddDepartment")
</p>
<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.DeptID)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.DeptName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MGRName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MGREMPNO)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    @Html.HiddenFor(modelItem => item.DeptID)
    @*<td>
            @Html.DisplayFor(modelItem => item.DeptID)
        </td>*@
    <td>
        @Html.DisplayFor(modelItem => item.DeptName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.MGRName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.MGREMPNO)
    </td>
    <td>
        @Html.ActionLink("Edit", "EditDeptDetails", new { id = item.DeptID }) |
        @Html.ActionLink("Delete", "DeleteDept", new { id = item.DeptID }, new { onclick = "return confirm('Are sure wants to delete?');" })
    </td>
</tr>
}

</table>

Views/Employee/AddEmployee.cshtml
@model CRUDMVC.Models.EmpModel


@using (Html.BeginForm("AddEmployee", "Employee", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>EmpModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @*<div class="form-group">
        @Html.LabelFor(model => model.Empid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Empid, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Empid, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10" style="color:green">
            @ViewBag.Message

        </div>
    </div>
    <div>
        @Html.ActionLink("Back to List", "GetAllEmpDetails")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>
}

Views/Employee/EditEmpDetails.cshtml
@model CRUDMVC.Models.EmpModel


@using (Html.BeginForm("EditEmpDetails", "Employee", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Update Employee Details</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Empid)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Update" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "GetAllEmpDetails")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Employee/GetAllEmpDetails.cshtml
@model IEnumerable<CRUDMVC.Models.EmpModel>

<p>
    @Html.ActionLink("Add New Employee", "AddEmployee")
   
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        @Html.HiddenFor(modelItem => item.Empid)
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditEmpDetails", new { id = item.Empid }) |
                @Html.ActionLink("Delete", "DeleteEmp", new { id = item.Empid }, new { onclick = "return confirm('Are sure wants to delete?');" })
            </td>
        </tr>
    }

</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Add Employee", "AddEmployee", "Employee")</li>
                    <li>@Html.ActionLink("Employee List", "GetAllEmpDetails", "Employee")</li>
                    <li>@Html.ActionLink("Add Department", "AddDepartment", "Department")</li>
                    <li>@Html.ActionLink("Department List", "ListDepartment", "Department")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>